{config, pkgs, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../base.nix
  ];

  age.secrets."lighthouse/ca.key".file = ../../secrets/lighthouse/ca.key;
  age.secrets."lighthouse/lighthouse.key".file = ../../secrets/lighthouse/lighthouse.key;

  machine_name = "lighthouse";
  services.nebula.networks.main = {
    enable = true;
    isLighthouse = true;
    key = config.age.secrets."lighthouse/lighthouse.key".path;
    cert = pkgs.writeTextFile 
      {name = "lighthouse.crt"; text = (builtins.readFile ../../public/lighthouse/lighthouse.crt);};
    ca = pkgs.writeTextFile 
      {name = "lighthouse_ca.crt"; text = (builtins.readFile ../../public/lighthouse/ca.crt);};
  };
  networking.interfaces.ens3.useDHCP = true;

  # Generated by nixos-infect
  boot.cleanTmpDir = true;
  zramSwap.enable = true;
  services.openssh.enable = true;
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRIelgbx9pq5DHpWYLU4RQplmZBqAp8Qp/uCOqdYBPOXIybkQbCqOMrBV28vv+V21tywA/1QX1gFIo9rVr5VZksXVlF2jcyDuQxVUn9Su17qxWF+BNtP9XLMx9KWl/t8HTzB/k6HwamotC11oJtwO6a6gAuNyUh2YNsDnImtQ/3W/Xq2CvyhwT/nB/i49g5bdAcnZiuOjOPI5Xig7Fjiii8KuQgLSMt1EjPZRkf5+8OH1iN2R6W1vHFPVvDaFtC0solY440juB3T7uLtyJ6JqA2YZyP/Y30h5OWGHwsyb2y7oWWLC97mJomcvLSRu/rGp9pzs6/FbWqR8hPrCUdoZEaKrtkwhGVNmlJlmlh8CO2nVIWZLZCihqP5X2x9dst5IGrS0YLmG0ymgOsVI/v7gIoqQJi2Tx2hh1p2ijTuAogvfLqQcvbmGfk/dSpSCqKkBA84bDg+EeNZHbrfzhoOUCzWb0nNIxDe9Op5EJRwUaNveHgehAivoXBQjbAa7UdWc= bender@nixos" 
  ];
}
